---

galaxy_info:
  author: PowerDNS Engineering Team
  description: Install and configure the PowerDNS Recursor
  company: PowerDNS.COM BV
  license: MIT
  min_ansible_version: 2.2
  platforms:
    - name: EL
      versions:
        - 7
        - 6
        - 8
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - trusty
        - bionic
        - focal
    - name: FreeBSD
      versions:
        - 11
        - 12
  galaxy_tags:
    - system
    - dns
    - pdns
    - powerdns
    - recursor
