---

- name: Install the SQLite dependencies on RedHat
  package:
    name: sqlite
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install the SQLite dependencies on Debian
  package:
    name: sqlite3
    state: present
  when: ansible_os_family == 'Debian'

- name: Ensure that the directories containing the PowerDNS SQLite databases exist
  file:
    name: "{{ item | dirname }}"
    owner: "{{ pdns_user }}"
    group: "{{ pdns_group }}"
    state: directory
    mode: 0750
  with_items: "{{ pdns_sqlite_databases_locations }}"

- block:
    - name: Define the PowerDNS SQLite schema file path on RedHat < 7 and PowerDNS < 4.2.0
      set_fact:
        _pdns_mysql_schema_file: "/usr/share/doc/pdns/schema.sqlite3.sql"
      when: ansible_distribution_major_version | int < 7
        and _pdns_running_version is version_compare('4.2.0', '<')

    - name: Define the PowerDNS SQLite schema file path on RedHat >= 7 or PowerDNS >= 4.2.0
      set_fact:
        _pdns_mysql_schema_file: "/usr/share/doc/pdns-backend-sqlite-{{ _pdns_running_version }}/schema.sqlite3.sql"
      when: ansible_distribution_major_version | int == 7
        or _pdns_running_version is version_compare('4.2.0', '>=')

    - name: Define the PowerDNS SQLite schema file path on RedHat 8 and PowerDNS >= 4.2.0
      set_fact:
        _pdns_mysql_schema_file: "/usr/share/doc/pdns-backend-sqlite/schema.sqlite3.sql"
      when:
        - ansible_distribution_major_version | int == 8
        - _pdns_running_version is version_compare('4.2.0', '>=')

    - name: Create the PowerDNS SQLite databases on RedHat
      shell: "sqlite3 {{ item }} < {{ _pdns_mysql_schema_file }}"
      args:
        creates: "{{ item }}"
      with_items: "{{ pdns_sqlite_databases_locations }}"

  when: ansible_os_family == "RedHat"

- block:

    - name: Create the PowerDNS SQLite databases on Debian
      shell: "sqlite3 {{ item }} < /usr/share/doc/pdns-backend-sqlite3/schema.sqlite3.sql"
      args:
        creates: "{{ item }}"
      with_items: "{{ pdns_sqlite_databases_locations }}"

  when: ansible_os_family == "Debian"

- block:
    - name: Initiate the SQLite database on Arch Linux
      shell: "sqlite3 {{ item }} < /usr/share/doc/powerdns/schema.sqlite3.sql"
      args:
        creates: "{{ item }}"
      with_items: "{{ pdns_sqlite_databases_locations }}"

  when: ansible_os_family == "Archlinux"

- name: Check the PowerDNS SQLite databases permissions
  file:
    name: "{{ item }}"
    owner: "{{ pdns_user }}"
    group: "{{ pdns_group }}"
    mode: 0640
    state: file
  with_items: "{{ pdns_sqlite_databases_locations }}"
