---

os: linux
dist: focal
language: python
python:
  - "3.6"

# Enable the docker service
services:
  - docker

# Replace aufs with the vfs docker storage driver
# to prevent systemd to fail starting docker in docker.
before_install:
  - sudo sed -i 's|DOCKER_OPTS=.*|DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock --storage-driver vfs"|g' /etc/default/docker
  - sudo service docker restart
  - docker info

# Parallel testing of the supported
# Ansible versions
env:
  jobs:
    - ANSIBLE=2.7 REC_VERSION=42
    - ANSIBLE=2.7 REC_VERSION=43
    - ANSIBLE=2.7 REC_VERSION=44
    - ANSIBLE=2.7 REC_VERSION=master

    - ANSIBLE=2.8 REC_VERSION=42
    - ANSIBLE=2.8 REC_VERSION=43
    - ANSIBLE=2.8 REC_VERSION=44
    - ANSIBLE=2.8 REC_VERSION=master

    - ANSIBLE=2.9 REC_VERSION=42
    - ANSIBLE=2.9 REC_VERSION=43
    - ANSIBLE=2.9 REC_VERSION=44
    - ANSIBLE=2.9 REC_VERSION=master

jobs:
  allow_failures:
    - env: REC_VERSION=master

# Install tox
install:
  - pip install tox-travis

# Test the current PowerDNS Recursor stable release
script:
  - tox -- molecule test -s pdns-rec-${REC_VERSION}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
