---

default_pdns_rec_package_name: "pdns-recursor"

pdns_rec_powerdns_repo_master:
  apt_repo_origin: "repo.powerdns.com"
  apt_repo: "deb [arch=amd64] https://repo.powerdns.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }}-rec-master main"
  gpg_key: "https://repo.powerdns.com/CBC8B383-pub.asc"
  gpg_key_id: "D47975F8DAE32700A563E64FFF389421CBC8B383"
  yum_repo_baseurl: "https://repo.powerdns.com/centos/$basearch/$releasever/rec-master"
  yum_debug_symbols_repo_baseurl: "https://repo.powerdns.com/centos/$basearch/$releasever/rec-master/debug"
  name: "powerdns-rec-master"

pdns_rec_powerdns_repo_40:
  apt_repo_origin: "repo.powerdns.com"
  apt_repo: "deb [arch=amd64] https://repo.powerdns.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }}-rec-40 main"
  gpg_key: "https://repo.powerdns.com/FD380FBB-pub.asc"
  gpg_key_id: "9FAAA5577E8FCF62093D036C1B0C6205FD380FBB"
  yum_repo_baseurl: "https://repo.powerdns.com/centos/$basearch/$releasever/rec-40"
  yum_debug_symbols_repo_baseurl: "https://repo.powerdns.com/centos/$basearch/$releasever/rec-40/debug"
  name: "powerdns-rec-40"

pdns_rec_powerdns_repo_41:
  apt_repo_origin: "repo.powerdns.com"
  apt_repo: "deb [arch=amd64] https://repo.powerdns.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }}-rec-41 main"
  gpg_key: "https://repo.powerdns.com/FD380FBB-pub.asc"
  gpg_key_id: "9FAAA5577E8FCF62093D036C1B0C6205FD380FBB"
  yum_repo_baseurl: "https://repo.powerdns.com/centos/$basearch/$releasever/rec-41"
  yum_debug_symbols_repo_baseurl: "https://repo.powerdns.com/centos/$basearch/$releasever/rec-41/debug"
  name: "powerdns-rec-41"

pdns_rec_powerdns_repo_42:
  apt_repo_origin: "repo.powerdns.com"
  apt_repo: "deb [arch=amd64] https://repo.powerdns.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }}-rec-42 main"
  gpg_key: "https://repo.powerdns.com/FD380FBB-pub.asc"
  gpg_key_id: "9FAAA5577E8FCF62093D036C1B0C6205FD380FBB"
  yum_repo_baseurl: "https://repo.powerdns.com/centos/$basearch/$releasever/rec-42"
  yum_debug_symbols_repo_baseurl: "https://repo.powerdns.com/centos/$basearch/$releasever/rec-42/debug"
  name: "powerdns-rec-42"

pdns_rec_powerdns_repo_43:
  apt_repo_origin: "repo.powerdns.com"
  apt_repo: "deb [arch=amd64] https://repo.powerdns.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }}-rec-43 main"
  gpg_key: "https://repo.powerdns.com/FD380FBB-pub.asc"
  gpg_key_id: "9FAAA5577E8FCF62093D036C1B0C6205FD380FBB"
  yum_repo_baseurl: "https://repo.powerdns.com/centos/$basearch/$releasever/rec-43"
  yum_debug_symbols_repo_baseurl: "https://repo.powerdns.com/centos/$basearch/$releasever/rec-43/debug"
  name: "powerdns-rec-43"

pdns_rec_powerdns_repo_44:
  apt_repo_origin: "repo.powerdns.com"
  apt_repo: "deb [arch=amd64] https://repo.powerdns.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }}-rec-44 main"
  gpg_key: "https://repo.powerdns.com/FD380FBB-pub.asc"
  gpg_key_id: "9FAAA5577E8FCF62093D036C1B0C6205FD380FBB"
  yum_repo_baseurl: "https://repo.powerdns.com/centos/$basearch/$releasever/rec-44"
  yum_debug_symbols_repo_baseurl: "https://repo.powerdns.com/centos/$basearch/$releasever/rec-44/debug"
  name: "powerdns-rec-44"

default_pdns_rec_service_overrides: >-
  {{  { 'User'  : pdns_rec_user
      , 'Group' : pdns_rec_group
      } if _pdns_rec_version is version('4.3', operator='ge')
        else {}
  }}
