---

- name: "Remove virtual machine {{ vm_name }}"
  vmware_guest:
    hostname: "{{ vcenter_fqdn }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    validate_certs: no
    datacenter: "{{ datacenter_name }}"
    state: "{{ item }}"
    folder: "{{ vm_folder_name }}"
    name: "{{ vm_name }}"
  delegate_to: localhost
  register: del_vm
  failed_when: false
  with_items:
    - poweredoff
    - absent
