---

- hosts: localhost
  gather_facts: yes
  vars_files:
    - default/main.yml
  tasks:
    - name: Create new VM
      import_tasks: create_vm.yml
      tags:
        - create

    - name: Delete VM
      import_tasks: delete_vm.yml
      tags:
        - never
        - delete

- hosts: VMs
  gather_facts: yes
  vars_files:
    - default/main.yml
  vars:
    ansible_ssh_user: root
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  pre_tasks:
    - name: Downloading required roles
      local_action: "command ansible-galaxy install -r {{ playbook_dir }}/files/requirements.yml --roles-path {{ playbook_dir }}/roles/"
      become: false
      run_once: True
      changed_when: False
      tags:
        - create
  tasks:
    - name: "Joining {{ ad_server.domain }}"
      import_tasks:
        file: join_ad.yml
      when: "'VMs' in group_names"
      tags:
        - create
