---

- hosts: localhost
  gather_facts: yes
  become: yes
  vars_files:
    - ~/.ansible_become_pass
    - default/main.yml
  vars:
    create_vms:
      - { name: ansible-test-vm }

  tasks:
    - name: Create new VM
      include_tasks: create_vm.yml
      vars:
        - vm_name: "{{ vm.name }}"
      args:
        apply:
          tags:
            - create
      loop: "{{ create_vms }}"
      loop_control:
        loop_var: vm
      tags:
        - create

    - name: Delete VM
      include_tasks: delete_vm.yml
      vars:
        - vm_name: "{{ vm.name }}"
      args:
        apply:
          tags:
            - delete
      loop: "{{ create_vms }}"
      loop_control:
        loop_var: vm
      tags:
        - never
        - delete

- import_playbook: provision.yml