---

- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Include vars files
      include_vars:
        file: "{{ playbook_dir }}/vars/ler53_vars.yml"

    - include: "{{ playbook_dir }}/ler53.yml"
      vars:
        ler53_cert_common_name: "{{ hostvars[item]['ler53_cert_common_name'] }}"
      with_items: "{{ groups['vic'] }}"
      become: yes
